window.fbConfig = {
    "showCRSToolTips": false,
    "autoRefreshIntervalNormal": 60,
    "autoRefreshIntervalInplay": 12,
    "autoRefreshIntervalInplay_login": 5,
    "autoRefreshIntervalES": 3,
    "esManualRefreshInterval": 2,
    "allupInfo": {
        "CHL": "8", "CHP": "0", "CRS": "6", "DHC": "8", "ECH": "8", "ECS": "6",
        "EDC": "8", "EHA": "8", "EHL": "8", "ENT": "8", "ETG": "8", "FCS": "6",
        "FGS": "8", "FHA": "8", "FHL": "8", "FTS": "8", "GPF": "8", "GPW": "8",
        "HAD": "8", "HDC": "8", "HFT": "6", "HHA": "8", "HIL": "8", "JKC": "8",
        "MSP": "0", "NTS": "8", "OOE": "8", "TNC": "8", "TPS": "0", "TQL": "0",
        "TSP": "0", "TTG": "8", "FCH": "8",  "FHH": "8", "FHC": "8", "CHD": "8", 
        "ECD": "8", "EHH": "8", "AGS": "8","LGS":"8","NGS": "8","HLH":'8',"HLA":'8',
        "FLH": "8", "FLA": "8", "ELH": "8", "ELA": "8", "CHH": "8", "CHA": "8", 
        "CFH": "8", "CFA": "8", "CEH": "8", "CEA": "8", "TEAMHIL":"8","TEAMFHL":'8',
        "TEAMCHL":"8", 'TEAMEHL': '8', 'TEAMECH': "8", "TEAMFCH": "8"
    },
    "OtherDateLimit": 15,
    "MaxPaginationLimit": 60,
    "MaxSearchResultPaginationLimit": 20,
    "MaxTournResultDays": 60,
    "InplayPools": ["HAD", "EHA", "CHP", "TQL", "FHA", "HHA", "HDC", "FHH", "EDC",
    "HIL", "EHL", "FHL", "CHL", "ECH", "FCH", "CRS", "ECS", "FCS",
    "FTS", "TTG", "ETG", "NTS", "ENT", 'CHD', 'FHC', 'ECD', 'EHH'],
    "AllOddsOrder": ["HAD","EHA","CHP","TQL","FHA","NTS","ENT","HHA",'EHH',"HDC","FHH","EDC","SGA","HIL","TEAMHIL","EHL","TEAMEHL","FHL","TEAMFHL","CHL","TEAMCHL","ECH","TEAMECH","FCH","TEAMFCH","CHD","FHC","ECD","CRS","ECS","FCS","FTS","TTG","ETG","OOE","FGS","NGS","LGS","AGS","HFT", "GS","MSP"],
    "BSBetTypeOrder": ["HAD","EHA","CHP","TQL","FHA","NTS","ENT","HHA",'EHH',"HDC","FHH","EDC","SGA","HIL","HLH","HLA","EHL","ELH", "ELA","FHL","FLH", "FLA","CHL","CHH", "CHA","ECH","CEH", "CEA","FCH","CFH", "CFA","CHD","FHC","ECD","CRS","ECS","FCS","FTS","TTG","ETG","OOE","FGS","NGS","LGS","AGS","HFT", "GS","MSP"],
    "LastOddsOrder": ["HAD","EHA","TQL","FHA","HHA","EHH","HDC","EDC","FHH","SGA",,"HIL","TEAMHIL","EHL","TEAMEHL","FHL","TEAMFHL","CHL","TEAMCHL","ECH","TEAMECH","FCH","TEAMFCH","CHD","ECD","FHC","CRS","ECS","FCS","FTS","NTS","ENT","ETS","TTG","ETG","OOE","FGS","LGS","AGS","HFT","MSP"],
    "LastOddsPools": ["HAD","EHA","TQL","FHA","HHA","EHH","HDC","EDC","FHH","SGA",,"HIL",'HLH', "HLA","EHL","ELH", "ELA","FHL","FLH", "FLA","CHL","CHH", "CHA","ECH","CEH", "CEA","FCH","CFH", "CFA","CHD","ECD","FHC","CRS","ECS","FCS","FTS","NTS","ENT","ETS","TTG","ETG","OOE","FGS","LGS","AGS","HFT","MSP"],

    "AllTournamentOrder": ["CHP", "TQL", "GPW", "GPF", "TPS", "TSP"],
    "ShowTeamNameType": ["CHP", "TQL", "GPW", "GPF", "TPS", "TSP", "FGS","LGS","NGS","AGS", "MSP", "SGA"],
    "HandicapPools": ["HHA", "HDC", "EDC", 'FHH', 'CHD', 'FHC', 'ECD', 'EHH'],
    "HandicapOnlyPools": ["HDC", "FHH", "EDC"],
    "GoalLinePools": ["HIL", "EHL", "FHL", "CHL", "ECH", "FCH"],
    "TeamGoalLinePools": ["HLH", "HLA", "FLH", "FLA", "ELH", "ELA","CHH", "CHA", "CFH", "CFA", "CEH", "CEA"],
    "TeamHiloPools":{
        "HomeTeamPools": ["HLH", "FLH", "ELH", "CHH", "CFH", "CEH"],
        "AwayTeamPools": ["HLA", "FLA", "ELA", "CHA", "CFA", "CEA"],
        "TeamCornerPools": ["TEAMCHL", "TEAMECH", "TEAMFCH"],
        "TEAMHIL":['HLH', "HLA"],
        "TEAMEHL":["ELH", "ELA"],
        "TEAMFHL":["FLH", "FLA"],
        "TEAMCHL":["CHH", "CHA"],
        "TEAMECH":["CEH", "CEA"],
        "TEAMFCH":["CFH", "CFA"] },
    "CornerPools": ["CHL", "FCH", "ECH","CHD", "FHC","ECD","CHH", "CHA","CEH", "CEA","CFH", "CFA"],
    "CornerHandicapPools": ["CHD", "FHC","ECD"],
    "CornerExtraTimePools": ["ECH", "ECD","CEH", "CEA"],
    "PlayerPools": ["FGS","MSP"],
    "TotalGoalsPools": ["TTG","ETG"],
    "CorrectScorePools": ["CRS", "FCS", "ECS"],
    "FirstScorerPools": ["FGS","LGS","NGS","AGS"],
    "NTSPools": ["NTS", "ENT", "ETS"],
    "SpecialPools": ["MSP"],
    "SGAPools": ["SGA"],
    "ResultDetailPools": ["HAD","EHA","FHA","NTS","ENT","CRS","ECS","FCS","FTS","TTG","ETG","OOE","FGS","LGS","NGS","AGS","HFT","MSP","SGA", "CHL", "FCH", "ECH","CHD", "FHC","ECD", 'EHH', 'FHH', "HLH", "HLA", "FLH", "FLA", "ELH", "ELA","CHH", "CHA", "CFH", "CFA", "CEH", "CEA"],
    "ResultDeatilQueryPools":['HAD', 'SGA', 'EHA', 'FHA', 'TQL', 'CRS', 'FCS', 'ECS', 'TTG', 'ETG', 'OOE', 'FGS',"NGS","AGS", "LGS", 'HFT', 'FTS', 'NTS', 'ENT', 'ETS', 'MSP', 'CHL', 'ECH', 'FCH', 'FHC', 'CHD', 'ECD', 'EHH', 'FHH', "HLH", "HLA", "FLH", "FLA", "ELH", "ELA","CHH", "CHA", "CFH", "CFA", "CEH", "CEA"],
    "AllupEnabledPools": ["HAD","EHA","FHA","NTS","ENT","HHA","EHH","HDC","FHH","EDC","HIL","EHL","FHL","CHL","FCH","ECH","CHD","FHC","ECD","CRS","ECS","FCS","FTS","TTG","ETG","OOE","FGS","NGS","LGS","AGS","HFT", "HLH", "HLA", "FLH", "FLA", "ELH", "ELA","CHH", "CHA", "CFH", "CFA", "CEH", "CEA"],
    "MixAllupPools": ["HAD","FHA","HHA","HDC","FHH","HIL","TEAMHIL","FHL","TEAMFHL","CHL","TEAMCHL","FCH","TEAMFCH","CHD","FHC","CRS","FCS","FTS","TTG","OOE","FGS","NGS","LGS","AGS","HFT"],
    "MixAllupAllPools": ["HAD","FHA","HHA","HDC","FHH","HIL",'HLH', "HLA","FHL","FLH", "FLA","CHL","CHH", "CHA","FCH","CFH", "CFA","CHD","FHC","CRS","FCS","FTS","TTG","OOE","FGS","NGS","LGS","AGS","HFT", "EHA","EHH","EDC","ELH","ELA","EHL","ECH","CEA", 'CEH',"ECD","ECS","ETG","ENT","ETS"],
    "TournamentAllupPools":["GPF","GPW"],
    "SingleMatchPages": ["ALLODDS", "INPLAY_ALL"],
    "AllOddsPages": ["ALLODDS", "INPLAY_ALL", "RESULTS"],
    "InplayPages": ["INPLAY", "INPLAY_ALL"],
    "TOURNAMENT_PAGE": ['TOURNAMENT', 'CHP', 'TQL', 'FINALIST', 'WINCNTY', 'WINCNTT'],
    "FB_MATCH_RESULT_PAGE": ['RESULTS', 'FGSRES', 'LGSRES', 'NGSRES', 'AGSRES'],
    "FB_PLAYER_RESULT_PAGE": [ 'FGSRES', 'LGSRES', 'NGSRES', 'AGSRES'],
    "FB_PM_RESULT_PAGE": ['DHCRES', 'HFMRES'],
    "FB_TOURN_RESULT_PAGE": ['CHPRES', 'TOURNRES'],
    "MixAllUpPages": ["MIXALLUP"],
    "MixAllUpDetailPages": ["MIXALLUP_DETAIL"],
    "MixAllup6LegPools": ["CRS", "FCS", "HFT"],
    "TTGCombStrs": ["0", "1", "2", "3", "4", "5", "6", "7+"],
    "HFTCombStrs": ["H:H", "H:D", "H:A", "D:H", "D:D", "D:A", "A:H", "A:D", "A:A"],
    "ResultDetailResultTable":{
        "left":["HAD", "FHA", "CRS", "FCS", "HFT", "TTG", "OOE", "FTS","NTS", "FGS","NGS","LGS","AGS", "TQL"],
        "right": ["FTS","NTS"],
        "eLeft": ["EHA","ECS", "ETG", "ENT"],
        "eRight": ["ENT"]
    },
    "ExtraTimePools": ["EHA","EHH","EDC","ELH","ELA","EHL","ECH","CEA", 'CEH',"ECD","ECS","ETG","ENT","ETS"],
    "FullTimePools": ["HAD","CHP","TQL","NTS","HHA","HDC","HIL","CHL","CHD","CRS","FTS","TTG","OOE","HFT"],
    "FirstHalfPools": ["FHA","FHL","FCH","FHH", "FHC","FCS"],
    "CashOutBetTypeList": ["OFM", "HOME", "HAD","FHA","SGA","FGS","LGS","NGS","AGS","FTS","NTS","MSP","HDC","FHH","HHA","HIL","FHL","CHL","FCH","CHD","FHC","CRS","FCS","TTG","OOE","HFT","INPLAY","MIXALLUP","TEAMHIL","TEAMFHL","TEAMCHL","TEAMFCH"],
    "crsOddsOrder": ['00:00', '01:00', '00:01', '02:00', '01:01', '00:02', '03:00', '02:01', '01:02', '00:03',
    '04:00', '03:01', '02:02', '01:03', '00:04', '05:00', '04:01', '03:02', '02:03', '01:04',
    '00:05', '05:01', '04:02', '03:03', '02:04', '01:05', '05:02', '02:05', 'OHN', 'HOAN', 'OAN', 'AOHN', 'HO', 'HOAS', 'DO', 'AO', 'AOHS'],
    "GSPools":['FGS',"NGS",'LGS','AGS'],
    "MatchBetTypeFilteringTab": [{
        "key": 'ALL',
        "ch": '全部',
        "en": 'All',
        "sequence": 1,
        "filterType": [],
        "excludeType":['GS']
    }, {
        "key": 'FH',
        "ch": '半場',
        "en": 'First Half',
        "sequence": 2,
        "filterType": ["FHA","FHL","TEAMFHL","FCH","TEAMFCH","FHH", "FHC","FCS"],
    },{
        "key": 'FT',
        "ch": '全場',
        "en": 'Full Time',
        "sequence": 3,
        "filterType": ["HAD","CHP","TQL","NTS","HHA","HDC","HIL","TEAMHIL","CHL","TEAMCHL","CHD","CRS","FTS","TTG","OOE",'FGS',"NGS",'AGS','LGS',"HFT"],
    }, {
        "key": 'CORNER',
        "ch": '角球',
        "en":'Corner',
        "sequence": 4,
        "filterType": ["CHL", "TEAMCHL", "FCH", "TEAMFCH", "CHD", "FHC"],
    },{
        "key": 'PLAYER',
        "ch": '球員',
        "en":'Player',
        "sequence": 5,
        "filterType": ["FGS","LGS","NGS","AGS",'GS',"MSP"],
    },{
        "key": 'SGA',
        "ch": '同場過關',
        "en":'SGA',
        "sequence": 6,
        "filterType": ["SGA"],
    }],
    "PlayerBetTypeFilteringTab":[
        {
            "key": 'GS',
            "ch": '全部',
            "en": 'All',
            "sequence": 1,
            "filterType": ["FGS", 'LGS',"NGS", "AGS"]
        }, {
            "key": 'FGS',
            "ch": '首名入球',
            "en": 'First Scorer',
            "sequence": 2,
            "filterType": ["FGS"]
        },{
            "key": 'LGS',
            "ch": '最後入球球員',
            "en": 'Last Scorer',
            "sequence": 3,
            "filterType": ["FGS"]
        }, {
            "key": 'NGS',
            "ch": '下一名入球球員',
            "en": 'Next Scorer',
            "sequence": 4,
            "filterType": ["FGS"]
        }, {
            "key": 'AGS',
            "ch": '任何時間入球球員',
            "en":'Anytime Scorer',
            "sequence": 5,
            "filterType": ["FGS"]
        }
    ],
    "AllupFormula": [
        [],
        [],
        ["2x1", "2x3"],
        ["3x1", "3x3", "3x4", "3x6", "3x7"],
        ["4x1", "4x4", "4x5", "4x6", "4x10", "4x11", "4x14", "4x15"],
        ["5x1", "5x5", "5x6", "5x10", "5x15", "5x16", "5x20", "5x25", "5x26", "5x30", "5x31"],
        ["6x1", "6x6", "6x7", "6x15", "6x20", "6x21", "6x22", "6x35", "6x41", "6x42", "6x50", "6x56", "6x57", "6x62", "6x63"],
        ["7x1", "7x7", "7x8", "7x21", "7x35", "7x120", "7x127"],
        ["8x1", "8x8", "8x9", "8x28", "8x56", "8x70", "8x247", "8x255"]
    ],
    "AllupCombination": [
        ["2#1", "0", "2", "#1######"],
        ["3#1", "0", "3", "##1#####"],
        ["4#1", "0", "4", "###1####"],
        ["5#1", "0", "5", "####1###"],
        ["6#1", "0", "6", "#####1##"],
        ["7#1", "0", "7", "######1#"],
        ["8#1", "0", "8", "#######1"],
        ["2#3", "1", "2", "2#1######"],
        ["3#6", "1", "3", "3#3######"],
        ["3#7", "1", "3", "3#3#1#####"],
        ["4#10", "1", "4", "4#6######"],
        ["4#14", "1", "4", "4#6#4#####"],
        ["4#15", "1", "4", "4#6#4#1####"],
        ["5#15", "1", "5", "5#10######"],
        ["5#25", "1", "5", "5#10#10#####"],
        ["5#30", "1", "5", "5#10#10#5####"],
        ["5#31", "1", "5", "5#10#10#5#1###"],
        ["6#21", "1", "6", "6#15######"],
        ["6#41", "1", "6", "6#15#20#####"],
        ["6#56", "1", "6", "6#15#20#15####"],
        ["6#62", "1", "6", "6#15#20#15#6###"],
        ["6#63", "1", "6", "6#15#20#15#6#1##"],
        ["7#127", "1", "7", "7#21#35#35#21#7#1#"],
        ["8#255", "1", "8", "8#28#56#70#56#28#8#1"],
        ["3#3", "2", "3", "#3######"],
        ["3#4", "2", "3", "#3#1#####"],
        ["4#6", "2", "4", "#6######"],
        ["4#11", "2", "4", "#6#4#1####"],
        ["5#10", "2", "5", "#10######"],
        ["5#20", "2", "5", "#10#10#####"],
        ["5#26", "2", "5", "#10#10#5#1###"],
        ["6#15", "2", "6", "#15######"],
        ["6#35", "2", "6", "#15#20#####"],
        ["6#50", "2", "6", "#15#20#15####"],
        ["6#57", "2", "6", "#15#20#15#6#1##"],
        ["7#120", "2", "7", "#21#35#35#21#7#1#"],
        ["8#247", "2", "8", "#28#56#70#56#28#8#1"],
        ["4#4","3","4","##4#####"],
        ["4#5","3","4","##4#1####"],
        ["5#16","3","5","##10#5#1###"],
        ["6#20","3","6","##20#####"],
        ["6#42","3","6","##20#15#6#1##"],
        ["5#5","4","5","###5####"],
        ["5#6","4","5","###5#1###"],
        ["6#22","4","6","###15#6#1##"],
        ["7#35","4","7","###35####"],
        ["8#70","4","8","###70####"],
        ["6#6","5","6","####6###"],
        ["6#7","5","6","####6#1##"],
        ["7#21","5","7","####21###"],
        ["8#56","5","8","####56###"],
        ["7#7","6","7","#####7##"],
        ["7#8","6","7","#####7#1#"],
        ["8#28","6","8","#####28##"],
        ["8#8","7","8","######8#"],
        ["8#9","7","8","######8#1"]
    ],
    "AllPoolsMinBet":{
        "CHL": 10, "CHP": 10, "CRS": 10, "DHC": 10, "ECH": 10, "ECS": 10,
        "EDC": 200, "EHA": 10, "EHL": 10, "ENT": 10, "ETG": 10, "FCS": 10,
        "FGS": 10, "FHA": 10, "FHL": 10, "FTS": 10, "GPF": 10, "GPW": 10,
        "HAD": 10, "HDC": 200, "HFT": 10, "HHA": 10, "HIL": 10, "JKC": 10,
        "MSP": 10, "NTS": 10, "OOE": 10, "TNC": 10, "TPS": 10, "TQL": 10,
        "FHH": 200, "CHD": 10, "FHC": 10, "ECD": 10, "EHH": 10,
        "TSP": 10, "TTG": 10, "FCH": 10, "ALUP": 10
    },
    "pushTopics": {
        "TOU_NEW": "hk/d/evnt/sport/evt/01/crd/fb/tourn",
        "MAT_NEW": "hk/d/evnt/sport/evt/01/crd/fb/match/+",
        "HAD_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/had",
        "TOU_UP": "hk/d/evnt/sport/evt/01/upd/fb/tourn/+",
        "HAD_POO_UP": "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/had/+",
        "MAT_UP":  "hk/d/evnt/sport/evt/01/upd/fb/+/+/+",
        "EHA_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/eha",
        "EHA_POO_UP": "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/eha/+",
        "FHA_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/fha",
        "FHA_POO_UP": "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/fha/+",
        "HHA_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/hha",
        "HHA_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/hha/+",
        "OFM_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/ofm",
        "OFM_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/ofm/+",
        "HDC_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/hdc",
        "HDC_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/hdc/+",
        "HIL_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/hil",
        "HIL_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/hil/+",
        "FHL_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/fhl",
        "FHL_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/fhl/+",
        "CHL_POO_NEW":"hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/chl",
        "CHL_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/chl/+",
        "CHL_POO_NEW":"hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/fch",
        "CHL_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/fch/+",
        "CRS_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/crs",
        "CRS_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/crs/+",
        "FCS_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/fcs",
        "FCS_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/fcs/+",
        "FTS_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/fts",
        "FTS_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/fts/+",
        "TTG_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/ttg",
        "TTG_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/ttg/+",
        "FGS_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/fgs",
        "FGS_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/fgs/+",
        "SGA_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/sga",
        "SGA_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/sga/+",
        "OOE_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/ooe",
        "OOE_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/ooe/+",
        "HFT_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/hft",
        "HFT_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/hft/+",
        "INPLAY_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/had",
        "INPLAY_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/had/+",
        "MSP_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/msp",
        "MSP_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/msp/+",
        "CHP_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/chp",
        "CHP_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/chp/+",
        "FINALIST_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/chp",
        "FINALIST_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/chp/+",
        "WINCNTY_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/chp",
        "WINCNTY_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/chp/+",
        "WINCNTT_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/chp",
        "WINCNTT_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/chp/+",
        "TQL_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/tql",
        "TQL_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/tql/+",
        "INPLAY_ALL_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/+",
        "INPLAY_ALL_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/+/+",
        "MIXALLUP_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/+",
        "MIXALLUP_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/+/+",
        "ALLODDS_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+/+",
        "ALLODDS_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/+/+",
        "TOURNAMENT_POO_NEW": "hk/d/prdt/wager/evt/01/crd/fb/fo/pool/+/+",
        "TOURNAMENT_POO_UP":  "hk/d/prdt/wager/evt/01/upd/fb/fo/pool/+/+/+"
    },
    "esTopics": {
        "requestPrefix": "hk/g/arr/txn/evt/01/upd/fo/early_stlmt/ofr_enq/17/{0}/{1}",
        "requestMessage": "{\"collationId\":1,\"jwt\":\"{0}\",\"betId\": {1}}",
        "getValueReply": "hk/g/arr/txn/evt/01/upd/fo/early_stlmt/ofr_enq/17/{0}/+/cal_val",
        "cashoutNormalPrefix": "hk/g/arr/txn/evt/01/upd/fo/early_stlmt/ofr_enq/norm_bet/17/{0}/{1}",
        "cashoutNormalReply": "hk/g/arr/txn/evt/01/upd/fo/early_stlmt/ofr_enq/norm_bet/17/{0}/+/acpt_upd",
        "cashoutInplayPrefix": "hk/g/arr/txn/evt/01/upd/fo/early_stlmt/ofr_enq/inplay_bet/17/{0}/{1}",
        "cashoutInplayReply": "hk/g/arr/txn/evt/01/upd/fo/early_stlmt/ofr_enq/inplay_bet/17/{0}/+/acpt_upd"
    }

};




