/** HKJC Chinese display names → English names for external logo lookup. */
const HKJC_TEAM_EN: Record<string, string> = {
  伊拉克: "Iraq",
  佛得角: "Cape Verde",
  伊朗: "Iran",
  克羅地亞: "Croatia",
  加拿大: "Canada",
  加納: "Ghana",
  南非: "South Africa",
  南韓: "South Korea",
  卡塔爾: "Qatar",
  厄瓜多爾: "Ecuador",
  哥倫比亞: "Colombia",
  土耳其: "Turkey",
  塞內加爾: "Senegal",
  墨西哥: "Mexico",
  奧地利: "Austria",
  巴拉圭: "Paraguay",
  巴拿馬: "Panama",
  巴西: "Brazil",
  庫拉索: "Curaçao",
  德國: "Germany",
  挪威: "Norway",
  捷克: "Czech Republic",
  摩洛哥: "Morocco",
  日本: "Japan",
  比利時: "Belgium",
  沙特阿拉伯: "Saudi Arabia",
  法國: "France",
  波斯尼亞: "Bosnia and Herzegovina",
  海地: "Haiti",
  澳洲: "Australia",
  烏拉圭: "Uruguay",
  烏茲別克: "Uzbekistan",
  瑞典: "Sweden",
  瑞士: "Switzerland",
  科特迪瓦: "Ivory Coast",
  突尼西亞: "Tunisia",
  約旦: "Jordan",
  蘇格蘭: "Scotland",
  英格蘭: "England",
  荷蘭: "Netherlands",
  西班牙: "Spain",
  葡萄牙: "Portugal",
  意大利: "Italy",
  阿根廷: "Argentina",
  美國: "United States",
  威爾斯: "Wales",
  波蘭: "Poland",
  烏克蘭: "Ukraine",
  丹麥: "Denmark",
  塞爾維亞: "Serbia",
  羅馬尼亞: "Romania",
  匈牙利: "Hungary",
  希臘: "Greece",
  愛爾蘭: "Ireland",
  北愛爾蘭: "Northern Ireland",
  冰島: "Iceland",
  斯洛伐克: "Slovakia",
  斯洛文尼亞: "Slovenia",
  克羅地亞女足: "Croatia",
  尼日利亞: "Nigeria",
  喀麥隆: "Cameroon",
  阿爾及利亞: "Algeria",
  埃及: "Egypt",
  哥斯達黎加: "Costa Rica",
  牙買加: "Jamaica",
  智利: "Chile",
  秘魯: "Peru",
  委內瑞拉: "Venezuela",
  新西蘭: "New Zealand",
  中國: "China",
  泰國: "Thailand",
  越南: "Vietnam",
  印尼: "Indonesia",
  馬來西亞: "Malaysia",
  印度: "India",
};

export function resolveEnglishTeamName(chineseName: string): string {
  const trimmed = chineseName.trim();
  if (!trimmed) return "";
  return HKJC_TEAM_EN[trimmed] ?? "";
}
